name: geospatial
channels:
  - conda-forge
dependencies:
  - altair
  - awscli
  - black-jupyter
  - bottleneck
  - bqplot
  - bump2version
  - codespell
  - contextily
  - cython  
  - dask
  - h5py
  - humanize
  - gcsfs 
  - google-api-python-client
  - jupyter_bokeh
  - matplotlib
  - ncurses
  - netcdf4
  - nodejs
  - numcodecs 
  - oauth2client
  - opencv
  - palettable
  - pandas
  - pathlib2
  - plotly
  - proplot
  - psycopg2
  - pycrypto
  - pyhdf
  - pyresample
  - pyproj
  - pysal
  - python >=3.7
  - s3fs
  - scikit-learn
  - scikit-image
  - scipy
  - seaborn
  - shapely
  - six
  - spectral
  - statsmodels
  - tqdm
  - udunits2
  - voila
  - wget
  - wxee 
  - xmovie
# geospatial Conda Packages
  - entwine
  - geos
  - gdal
  - pdal
  - proj 
  - cartopy
  - dask-geopandas
  - datashader
  - fiona
  - folium
  - earthengine-api
  - earthpy
  - easystac 
  - eemont
  - eomaps
  - geemap
  - gemgis
  - geoalchemy2
  - geopandas
  - geoviews
  - here-map-widget-for-jupyter
  - httplib2shim
  - hvplot
  - ipygany
  - ipyleaflet
  - ipynb-py-convert
  - ipyparallel
  - ipyvolume
  - ipyvtklink 
  - ipywidgets
  - keplergl
  - laspy
  - leafmap
  - localtileserver
  - mapboxgl
  - movingpandas
  - odc-stac
  - osmnx
  - owslib
  - panel
  - palettable
  - pillow <=8.4.0 # required by sentinelhub 
  - planet
  - planetary-computer
  - pydeck
  - pystac
  - python-mss
  - pyntcloud
  - pyvista
  - radiant-mlhub
  - rasterio
  - regionmask
  - rasterstats
  - rio-cogeo
  - rioxarray
  - s2cloudless
  - sarpy
  - satpy
  - sentinelsat
  - shapely
  - spyndex
  - sqlalchemy
  - stackstac
  - streamlit-folium
  - xarray
  - xarray-simlab
  - xarray-spatial
  - xarray-topo
  - vega_datasets
  - zarr 